### PR TITLE
Say what again? Entities are now JSON!

### PR DESCRIPTION
**Pull request by Repertoi-e**

### CODE REVIEW

**Comment by KiddieD** [comment]
Looks like a timnomn... Jk! Great work c:

**Comment by KiddieD** [comment]
If you're sure about it, I'll merge it

**Comment by Repertoi-e** [comment]
I'm sure but let's wait for someone to review it

**Comment by KiddieD** [comment]
Well I did
I can merge it haha

**Comment by Repertoi-e** [comment]
Ok do :D

**Comment by KiddieD** [comment]
Wait I forgot where to review a reqquest

**Comment by KiddieD** [comment]
You should be able to merge now c:

**Pull request merged**
