### PR TITLE
Entity sorting, cleaning up, UI 'rework', started work on In-Game Console

### PR DESCRIPTION
**Pull request by Repertoi-e**
There a **lot** of changes here:
- Moved entities scripts from `res/scripts` to `res/entities/scripts`
- Removed `flipOnVelocity` bool in SpriteComponent, it's functionality now must be implemented in the entity's script as follows: (where xa and ya are movement directions)
```
if xa > 0 then
    entity:setSpriteFlip(false) 
end
if xa < 0 then
    entity:setSpriteFlip(true) 
end
```
- Added a `transparency.frag` shader which is used by the In-Game console for a slight translucent effect
- Reorganized sound files in `res/sounds/` and renamed `SFX.h/.cpp/class`, `BGM.h/.cpp/class` to `SoundFX.h/.cpp/class`, `Music.h/.cpp/class` respectively
- New BIT(x) define in `Common.h` makes it easier to define enum values:
```
Inventory = BIT(3);
// same as:
Inventory = 1 << 3;
```
- Application access now happens with `Application::get().` instead of `Application::instance->` (*same with `State::Playing`)
- `getFont("")` and `getTexture("")` methods in Application for easier access to resources
- UI now uses events which doesn't allow input "penetration" and UI components are now stored in Panels which upon creation/deletion are added/removed from a vector in Application and are automatically updated/rendered
- New Cursor class allows changing mouse cursor 
- Reorganized Application class methods and members, moved Input related stuff to `Input.h/.cpp`
- Fixed some bugs in `StateMenu` with clicking the "Singleplayer" button and the game crashing
- Moved item and entity components to `src/components` so they can be shared between items and entities and made them use namespace `Components::`
- Entity render sorting based on Y position
- Started work on an In-Game console for developers (it will have custom commands and ability to reload .lua scripts during runtime)
- Removed `HostileComponent` as it is not needed with the future World Generation presets
- Added visual representation of the zombie's path following the player
- Event system using partially the SFML one but more advanced. Event dispatching works like this: (where `func` must have the following definition: `bool func(TypeOfEvent& e);`, example in `Panel.cpp:line 50`)
```cplusplus
void onEvent(Events::Event& event)
{
        EventDispatcher dispatcher(event);
	dispatcher.dispatch<TypeOfEvent>(func);            
}
``` 
- Reorganized files in `src/maths/` and renamed Maths.h, MathsFunc.h to maths.h, maths_func.h respectively
- Changed entities to use float rectangles instead of AABBs for collision boxes since they behaved like they used them (an AABB has min, max vectors while entities used the 'max' vector as width and height dimensions)
- Split up the rendering code from the main loop into a separate `render()` method for a more cleaned look (also did this to try multithreaded rendering, may look into it again in the future)
- New 'Renderer2D' class. Used for dynamic vertex array generation. Tiles now used it for rendering. This allows different tile types to have different render methods. I made the wall tile use it for a 3D effect. (you're gonna have to see it in game)
- The new tile renderer allows for dynamically picking which tiles should be rendered. ATM tiles which are outside the player view and tiles which are completely submerged in black light get skipped when rendering which boosted up the average FPS of the game.
- Added the old wall textures to `texture_atlas.png` as placeholder to test the new tile rendering system
- Fixed a slight bug (?) with lightning position being offset a little.
- Simplified `tileCollision()` method and added support for custom collision boxes for tiles, instead of using a default `{ 0, 0, 32, 32 }` one.
- Tiles can have multiple textures. Different tile types can use them however they desire. The wall tile uses the first texture specified in the .json as a 'side' texture and the second one as a 'top' texture:
`BrickWall.json`
```json
	"Textures": [
		[ 0, 6 ],
		[ 0, 5 ]
	],
```
Quick reminder: tile textures are defined by two integers specifying the coordinates of the texture in the tile atlas, starting from zero.
- Light map generation is now slightly faster with more references and less copying.

If anyone experiences significantly less FPS with these changes compared to previous versions of the game, tag me in discord.

### CODE REVIEW

**Comment by Repertoi-e** [comment]
Don't merge yet

**Comment by KiddieD** [comment]
WHy make a PR if you don't want to merge it in? You can submit a branch without the automatic PR.

**Comment by Repertoi-e** [comment]
I wanted to combine the commits into one and also do some other changes and I didn't want to make a second small PR just for one or two changes.

**Comment by Repertoi-e** [comment]
Ready for merge! (finally) Make sure to read the first comment for all the changes done in this commit.

**Comment by KiddieD** [comment]
So I can merge it now?

**Comment by Repertoi-e** [comment]
Yep!

**Pull request merged**
