### PR TITLE
Added links to CONTRIBUTING & CODESTYLE in README

### PR DESCRIPTION
**Pull request by Bravo555**

### CODE REVIEW

**Comment by Bravo555** [comment]
I don't know what do you mean by that. Am I supposed to correct the README file or the commit message?

**Comment by Repertoi-e** [comment]
I don't see a problem with either of these

**Comment by KiddieD** [comment]
I will show you what I mean when I'm home. C:

**Comment by KiddieD** [comment]
Stupid chrome. I retract.

**Pull request merged**
