### PR TITLE
Huge refactor #1 (April-May 2017)

### PR DESCRIPTION
**Pull request by Repertoi-e**

### CODE REVIEW

**Comment by KiddieD** [comment]
It means you code doesn't comply or is faulty

**Comment by Bravo555** [comment]
Error occurs because `Tile.h` is not in the same directory as `TilesMap.h`. If you want to go directory above, use `..` in the path.
Also, is that intentional? 
obraz

**Comment by Bravo555** [comment]
FTFY

**Comment by Repertoi-e** [comment]
Wow ty

**Comment by Bravo555** [comment]
The last thing is just correct the paths in files manually. There is now only one folder, `tile`.

**Comment by Repertoi-e** [comment]
Ok ready for merge :X

**Pull request merged**
