### PR TITLE
Apparently now #124 is fixed

### PR DESCRIPTION
**Pull request by Bravo555**

### CODE REVIEW

**Comment by Bravo555** [comment]
Cool thing: because of the issue no. and *fixed* keyword when you merge this, [issue will be closed automatically](https://www.google.pl/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiSkoSd_JXTAhVqCpoKHTb8A3EQFggcMAA&url=https%3A%2F%2Fhelp.github.com%2Farticles%2Fclosing-issues-via-commit-messages%2F&usg=AFQjCNEue9hoEER5gFP4btxbvyiF02qPjg&sig2=uWVDuagITH74lfT1J0cTjA).

**Comment by KiddieD** [comment]
And what exactly is the purpose of this

**Comment by Bravo555** [comment]
All the changes should be reviewed before they will be merged. You can request changes or approve them and they'll finally be merged. Because we have an org now, we can now create a team with the code reviewers and PRs will be controlled better and merged faster.

**Comment by kaizi99** [comment]
Dont we need to revert the revert first?

**Comment by Bravo555** [comment]
Ah, yes, this fixes a bug which is in `generateMap()`, we also need to revert this revert.

**Pull request merged**
