### PR TITLE
New player placement

### PR DESCRIPTION
**Pull request by kaizi99**

### CODE REVIEW

**Comment by Bravo555** [comment]
Are you sure that this is different from the reverted code and we need to do it like this, not via reverting the earlier revert?

**Comment by kaizi99** [comment]
I tested his fork on my computer(windows) and everything seems to work properly

**Comment by Bravo555** [comment]
The reverted function also has `placeEntities()` function that seems to be missing here. How about we first revert to the previous version of the `placePlayer()` and then apply that?

**Comment by kaizi99** [comment]
There is no need to revert anything here. This PR compiles, runs and does what is being specified. This is a completely new attempt to do that what we reverted.

**Comment by kaizi99** [comment]
revert
This master freshly cloned, pulled Hakers fork and this is what comes up, so everythings fine

**Pull request merged**
